"""Initial migration.

Revision ID: b8c2777aa728
Revises: 
Create Date: 2022-11-04 21:32:50.639283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c2777aa728'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_cidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sigla', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('nascimento', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=False),
    sa.Column('tipo_pessoa', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instituicaoDeEnsino', sa.String(length=80), nullable=False),
    sa.Column('curso', sa.String(length=50), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('pessoa_parent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_parent'], ['tb_pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_uf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=90), nullable=False),
    sa.Column('sigla', sa.String(length=6), nullable=False),
    sa.Column('cidade_parent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cidade_parent'], ['tb_cidade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_passageiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('cidadeOrigem', sa.String(length=90), nullable=False),
    sa.Column('cidadeDestino', sa.String(length=90), nullable=False),
    sa.Column('aluno_parent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_parent'], ['tb_aluno.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_rota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomeDestino', sa.String(length=200), nullable=False),
    sa.Column('qtdalunos', sa.String(length=11), nullable=False),
    sa.Column('prefeitura', sa.String(length=200), nullable=False),
    sa.Column('veiculo', sa.String(length=30), nullable=False),
    sa.Column('passageiro', sa.String(length=50), nullable=False),
    sa.Column('horaSaida', sa.DateTime(), nullable=False),
    sa.Column('horaChegada', sa.DateTime(), nullable=False),
    sa.Column('aluno_parent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_parent'], ['tb_aluno.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_instituicaoDeEnsino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=False),
    sa.Column('logradouro', sa.String(length=200), nullable=False),
    sa.Column('aluno_parent', sa.Integer(), nullable=True),
    sa.Column('rota_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_parent'], ['tb_aluno.id'], ),
    sa.ForeignKeyConstraint(['rota_id'], ['tb_rota.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_prefeitura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secretarios', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=False),
    sa.Column('nomePrefeito', sa.String(length=100), nullable=False),
    sa.Column('rota_parent', sa.Integer(), nullable=True),
    sa.Column('cidade_parent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cidade_parent'], ['tb_cidade.id'], ),
    sa.ForeignKeyConstraint(['rota_parent'], ['tb_rota.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nomePrefeito'),
    sa.UniqueConstraint('secretarios'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('tb_endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=False),
    sa.Column('complemento', sa.String(length=30), nullable=False),
    sa.Column('referencia', sa.String(length=300), nullable=False),
    sa.Column('logradouro', sa.String(length=100), nullable=False),
    sa.Column('pessoa_parent', sa.Integer(), nullable=True),
    sa.Column('instituicaoDeEnsino_parent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instituicaoDeEnsino_parent'], ['tb_instituicaoDeEnsino.id'], ),
    sa.ForeignKeyConstraint(['pessoa_parent'], ['tb_pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefeitura', sa.String(length=90), nullable=False),
    sa.Column('cargo', sa.String(length=30), nullable=False),
    sa.Column('pessoa_parent', sa.Integer(), nullable=True),
    sa.Column('prefeitura_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_parent'], ['tb_pessoa.id'], ),
    sa.ForeignKeyConstraint(['prefeitura_id'], ['tb_prefeitura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_gestorApp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gestorApp', sa.String(length=80), nullable=False),
    sa.Column('pessoa_parent', sa.Integer(), nullable=True),
    sa.Column('prefeitura_parent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_parent'], ['tb_pessoa.id'], ),
    sa.ForeignKeyConstraint(['prefeitura_parent'], ['tb_prefeitura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_prefeito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomePrefeito', sa.String(length=80), nullable=False),
    sa.Column('pessoa_parent_', sa.Integer(), nullable=True),
    sa.Column('prefeitura_parent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_parent_'], ['tb_pessoa.id'], ),
    sa.ForeignKeyConstraint(['prefeitura_parent'], ['tb_prefeitura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_motorista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rotas', sa.String(length=80), nullable=False),
    sa.Column('funcionario_parent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_parent'], ['tb_funcionario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cidade', sa.String(length=80), nullable=False),
    sa.Column('qtdPassageiros', sa.String(length=10), nullable=False),
    sa.Column('tipoVeiculo', sa.String(length=20), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('motorista_parent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['motorista_parent'], ['tb_motorista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_veiculo')
    op.drop_table('tb_motorista')
    op.drop_table('tb_prefeito')
    op.drop_table('tb_gestorApp')
    op.drop_table('tb_funcionario')
    op.drop_table('tb_endereco')
    op.drop_table('tb_prefeitura')
    op.drop_table('tb_instituicaoDeEnsino')
    op.drop_table('tb_rota')
    op.drop_table('tb_passageiro')
    op.drop_table('tb_uf')
    op.drop_table('tb_aluno')
    op.drop_table('tb_pessoa')
    op.drop_table('tb_cidade')
    # ### end Alembic commands ###
